288260-message-to-creator-and-approver
DEFRA/est-mit-web pull request #71
Opened 2024-01-10 14:43 UTC by JasmeetKaur-Defra

2024-01-10 16:35 UTC, andygibbonsdefra requested changes

2024-01-10 16:35 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                .WithApproverEmail(invoice.ApproverEmail)
Ah, no. We don't want to pass both Approver and Creator emails to the Notificaiton. So I think this is better just being two separate Nofitications (via two NotificaitonBuilders) and then pass both to the UpdateAndNofify. I think the enum method is just going to be confusing.

2024-01-10 17:20 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                .WithEmailRecipient(invoice.CreatedBy)
This should be invoice.ApprovalRequestedByEmail

2024-01-10 17:23 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Reason = reason
Did this get changed from Justification to Reason for.... a reason? The Notification service picks it up and inserts it into the email body OK?

2024-01-10 17:24 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Reason = reason
Because I didn't see a corresponding "Justification to Reason" code change in Notification service.

2024-01-11 11:36 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +            var addedToQueue = await _eventQueueService.AddMessageToQueueAsync("invoicenotification", requesterNotification.ToMessage());
We should probably add both notifications to the EventQueue log. ie. Approver as well as Requester

2024-01-11 16:18 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Link = $"{_context.HttpContext.GetBaseURI()}/invoice/summary/{invoice.SchemeType}/{invoice.Id}/user-invoices",
Should this have "/user-invoices"  on the end? Don't think it does anything.

2024-01-11 16:18 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Link = $"{_context.HttpContext.GetBaseURI()}/invoice/summary/{invoice.SchemeType}/{invoice.Id}/user-invoices",
also, not sure this should have "/user-invoices" on the end....

2024-01-11 16:19 UTC, andygibbonsdefra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Link = $"{_context.HttpContext.GetBaseURI()}/invoice/summary/{invoice.SchemeType}/{invoice.Id}/user-invoices",
"/user-invoices" suffix not needed?

2024-01-12 15:36 UTC, JasmeetKaur-Defra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Link = $"{_context.HttpContext.GetBaseURI()}/invoice/summary/{invoice.SchemeType}/{invoice.Id}/user-invoices",
Addressed

2024-01-12 15:36 UTC, JasmeetKaur-Defra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Link = $"{_context.HttpContext.GetBaseURI()}/invoice/summary/{invoice.SchemeType}/{invoice.Id}/user-invoices",
Addressed

2024-01-12 15:36 UTC, JasmeetKaur-Defra commented on EST.MIT.Web/Services/ApprovalService.cs
> +            var addedToQueue = await _eventQueueService.AddMessageToQueueAsync("invoicenotification", requesterNotification.ToMessage());
Addressed

2024-01-12 15:36 UTC, JasmeetKaur-Defra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                    Reason = reason
Addressed

2024-01-12 15:36 UTC, JasmeetKaur-Defra commented on EST.MIT.Web/Services/ApprovalService.cs
> +                                .WithApproverEmail(invoice.ApproverEmail)
Addressed

2024-01-12 15:36 UTC, andygibbonsdefra approved these changes

2024-01-12 15:37 UTC, merged